#!/bin/sh

# 用 `` 可以将命令的输出结果赋值给变量
# 获取当前提交的 commit msg
commit_msg=$(cat "$1")

# 获取用户 email
email=$(git config user.email)

# feat: feature 新功能提交
# fix: 修复 bug 的提交
# perf: 性能优化的提交
# refactor: 代码重构的提交
# merge: 合并分支的提交
# docs: 文档修改的提交
# style: 代码格式修改，注意不是 css 修改的提交
# test: 测试用例的修改
# build: 构建系统或者包依赖更新
# revert: 恢复上一次提交
# ci: 持续集成相关文件修改
# chore: 更新构建脚本，但是不会更新产品代码
# release: 发布新版本
# workflow: 工作流相关文件修改
msg_re="^(feat|fix|perf|refactor|merge|docs|style|test|build|revert|ci|chore|release|workflow)(\(.+\))?: .{1,100}"

if [[ ! $commit_msg =~ $msg_re ]]
then
	echo "不合法的 commit 消息提交格式，请使用正确的格式，请使用 feat|fix|perf|refactor|merge|docs|style 加冒号等开头格式"

	# 异常退出
	exit 1
fi
